//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyDescription("EQATEC - Tracer")]
[assembly: AssemblyCompany("EQATEC A/S")]
[assembly: AssemblyProduct("EQATEC - Tracer")]
[assembly: AssemblyCopyright("Copyright (C) 2005-2008, EQATEC A/S, DENMARK")]
[assembly: AssemblyTrademark("Copyright (C) 2005-2008, EQATEC A/S, DENMARK")]
[assembly: AssemblyVersion("1.2.405.0")]


